version: '3'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: {{DOCKER_ID}}/multi-nginx:{{TRAVIS_BUILD_NUMBER}}
    ports:
      - '3000:80'
  api:
    image: {{DOCKER_ID}}/multi-server:{{TRAVIS_BUILD_NUMBER}}    
    env_file:
        - .env
    #environment:
    #  - REDIS_HOST=redis
    #  - REDIS_PORT=6379
    #  - PGHOST=postgres
    #  - PGPORT=5432     
    #  - PGDATABASE=postgres
    #  - PGUSER={{PG_USER}}   
    #  - PGPASSWORD={{PG_PASSWORD}}
  client:
    stdin_open: true
    image: {{DOCKER_ID}}/multi-client:{{TRAVIS_BUILD_NUMBER}}    
  worker:
    image: {{DOCKER_ID}}/multi-worker:{{TRAVIS_BUILD_NUMBER}}
    env_file:
        - .env
    #environment:
    #  - REDIS_HOST=redis
    #  - REDIS_PORT=6379
