version: '3'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: {{DOCKER_ID}}/multi-nginx:latest
    ports:
      - '3000:80'
  api:
    image: {{DOCKER_ID}}/multi-server:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD={{PG_PASSWORD}}
      - PGPORT=5432
  client:
    stdin_open: true
    image: {{DOCKER_ID}}/multi-client:latest    
  worker:
    image: {{DOCKER_ID}}/multi-worker:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
